# Generated by Django 5.2.5 on 2025-08-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelOptions',
            fields=[
                ('travelid', models.BigAutoField(primary_key=True, serialize=False)),
                ('travel_type', models.CharField(choices=[('A', 'Flight'), ('B', 'Train'), ('C', 'Bus')], default='C', max_length=10)),
                ('source', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('available_seats', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
